Добавить проверку на существование индексов
kolesa-team/cloud-payments-client pull request #6
Opened 2019-02-05 04:58 UTC by D1kz

Добавил проверку индексов Success, Messsage, Model в $response в Manager.php

2019-02-05 05:09 UTC, JohnMars requested changes

2019-02-05 05:09 UTC, JohnMars commented on src/Manager.php
> +        if (array_key_exists('Success', $response) && !$response['Success']) {
Везде одна и та же проверка
Нельзя ли массив response переделать на класс и добавить к нем метод isSuccess?

2019-02-05 06:18 UTC, D1kz commented on src/Manager.php
> +        if (array_key_exists('Success', $response) && !$response['Success']) {
@JohnMars для форкнутой библиотечки звучит немного заморочено. могу вынести в protected метод эти проверки.
@iborodikhin ты что думаешь?

2019-02-08 06:22 UTC, iborodikhin commented on src/Manager.php
> +        if (array_key_exists('Success', $response) && !$response['Success']) {
Изменение параметра повлечет нарушение обратной совместимости, поэтому оставим как есть.

2019-02-08 06:22 UTC, iborodikhin approved these changes

2019-02-08 06:22 UTC, merged